language: node_js

node_js:
  - "10"
  - "12"
  - "13"

jobs:
  include:
    - stage: deploy
      script: yarn auto shipit
      node_js: "10"
      skip-cleanup: true
      on:
        branch: master
